version: 2
jobs:
  # build:
  #   docker:
  #     - image: circleci/python:3.6.1
      
  #   steps:
  #     - checkout

  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "requirements.txt" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-

  #     - run:
  #         name: install dependencies
  #         command: |
  #           python3 -m venv venv
  #           . venv/bin/activate
  #           pip install -r requirements.txt
  #           pip install .

  #     - save_cache:
  #         paths:
  #           - ./venv
  #         key: v1-dependencies-{{ checksum "requirements.txt" }}
        
  #     # run tests!
  #     - run:
  #         name: run tests
  #         command: |
  #           . venv/bin/activate
  #           pytest
  
  build:
    docker:
      - image: circleci/golang:1.11
    
    working_directory: /go/src/github.com/gusostow/one-click

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
    
    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS_DIR

      - run:
          name: install dependencies
          command: |
            wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
            sudo unzip terraform_0.11.11_linux_amd64.zip -d /usr/local/bin
            go get github.com/tools/godep
            dep ensure
      
      - run:
          name: run infrastructure tests
          command: |
            go test -v ./...